"""Physical infusion supports, retained details and ordered rigid-body clearances.

The historical JSON fixture contains immutable mesh fingerprints, never paths to
deployment assets. Every exercised candidate mesh is generated by current code.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import cadquery as cq
import pytest
import trimesh
import vtk
from vtk.util.numpy_support import numpy_to_vtk, vtk_to_numpy

from holocue.assets import load_asset
from holocue.config import load_policy, load_scene
from holocue.modeling import make_environment, make_object
from holocue.models import CueSemantic, Decision, Session
from holocue.projection import packet
from holocue.render_validation import polydata
from holocue.spatial import matrix, trajectory
from holocue.state import apply_decision
from scripts.tests.audit_geometry import parts


def _meshes(scene, pose=None):
    result={}
    for node in scene.graph.nodes_geometry:
        transform,name=scene.graph[node]
        mesh=scene.geometry[name].copy()
        mesh.apply_transform(transform if pose is None else matrix(pose)@transform)
        result[str(node)]=mesh
    return result


def _fingerprint(mesh):
    """Hash explicit arrays/material properties, independent of GLB packing."""
    result={key:hashlib.sha256(np.asarray(getattr(mesh,key),dtype=dtype).tobytes()).hexdigest()
            for key,dtype in [('vertices','<f8'),('faces','<i8'),('vertex_normals','<f8')]}
    result['uv']=None if mesh.visual.uv is None else hashlib.sha256(
        np.asarray(mesh.visual.uv,dtype='<f8').tobytes()).hexdigest()
    material=mesh.visual.material
    texture=getattr(material,'baseColorTexture',None)
    properties={'name':material.name,'baseColorFactor':np.asarray(material.baseColorFactor).tolist(),
                'metallicFactor':material.metallicFactor,'roughnessFactor':material.roughnessFactor,
                'doubleSided':material.doubleSided,'alphaMode':material.alphaMode,
                'texture_sha256':None if texture is None else hashlib.sha256(np.asarray(texture).tobytes()).hexdigest()}
    result['material']=hashlib.sha256(json.dumps(properties,sort_keys=True).encode()).hexdigest()
    return result


def _object_contracts(spec):
    return {obj.object_id:{'pose':obj.pose.model_dump(mode='json'),
                          'interaction':obj.interaction.model_dump(mode='json'),
                          'size_m':list(obj.size_m)} for obj in spec.objects}


@pytest.fixture(scope='module')
def infusion(tmp_path_factory):
    directory=tmp_path_factory.mktemp('infusion-support')
    spec=load_scene('infusion_ward')
    policy=load_policy()
    baseline=json.loads((Path(__file__).parent/'fixtures/infusion_support_baseline.json').read_text())
    generated={};roundtrip={};local_roundtrip={};local_generated={}
    assemblies=[(obj.object_id,make_object(obj),obj.pose) for obj in spec.objects]
    assemblies.append(('workstation',make_environment(spec),spec.environment[0].pose))
    for identifier,assembly,pose in assemblies:
        path=directory/f'{identifier}.glb'
        assembly.save(path)
        loaded=load_asset(str(path),spec.asset_axes)
        generated.update({f'{identifier}/{node}':mesh for node,mesh in _meshes(assembly.scene,pose).items()})
        roundtrip.update({f'{identifier}/{node}':mesh for node,mesh in _meshes(loaded,pose).items()})
        local_roundtrip[identifier]=_meshes(loaded)
        local_generated[identifier]=_meshes(assembly.scene)
    historical_path=Path(__file__).parent/'fixtures/infusion_stopcock_before_union.glb'
    assert hashlib.sha256(historical_path.read_bytes()).hexdigest()==baseline['source_assets_sha256']['STOPCOCK']
    historical=_meshes(load_asset(str(historical_path),spec.asset_axes))
    return {'spec':spec,'policy':policy,'baseline':baseline,'directory':directory,
            'generated':generated,'roundtrip':roundtrip,'local_roundtrip':local_roundtrip,
            'local_generated':local_generated,'historical_stopcock':historical}


def test_infusion_task_frames_and_parameters_are_preserved(infusion):
    assert _object_contracts(infusion['spec'])==infusion['baseline']['object_contracts']
    assert infusion['spec'].task_contract.model_dump(mode='json')==infusion['baseline']['task_contract']
    assert infusion['spec'].asset_axes==infusion['baseline']['asset_axes']


@pytest.mark.parametrize('identifier',['workstation','STOPCOCK'])
def test_infusion_original_details_survive_glb_roundtrip(infusion,identifier):
    actual=infusion['local_roundtrip'][identifier]
    expected=infusion['baseline']['mesh_fingerprints'][identifier]
    if identifier=='STOPCOCK':
        # The old two meshes are immutable reference surfaces. Their internal
        # overlap is intentionally removed; visible shape/material still match.
        for node,signature in expected.items():
            assert _fingerprint(infusion['historical_stopcock'][node])==signature
        _assert_original_union_exterior(infusion,actual)
        return
    for node,signature in expected.items():
        assert node in actual,('removed original node',identifier,node)
        assert _fingerprint(actual[node])==signature,('changed original detail',identifier,node)


CONTACT_GROUPS={
    'monitor':[
        ('MONITOR/0000_instrument_case','0026_monitor_support'),
        ('0026_monitor_support','0027_monitor_stand'),
        ('0027_monitor_stand','0031_monitor_stand_extension'),
        ('0031_monitor_stand_extension','0030_monitor_floor_base'),
        ('0030_monitor_floor_base','0000_training_room_floor')],
    'pump_and_slot':[
        ('SLOT2/0004_panel','0034_slot_chassis_mount'),
        ('0034_slot_chassis_mount','0025_pump_chassis'),
        ('0025_pump_chassis','0033_pump_pole_bracket'),
        ('0033_pump_pole_bracket','0032_pump_pole_clamp'),
        ('0032_pump_pole_clamp','0007_iv_pole')],
    'stopcock':[
        ('STOPCOCK/0001_handle_pointer','STOPCOCK/0000_rotor'),
        ('STOPCOCK/0000_rotor','0037_stopcock_rotor_journal'),
        ('0037_stopcock_rotor_journal','0028_static_stopcock_body'),
        ('0028_static_stopcock_body','0036_stopcock_pole_bracket'),
        ('0036_stopcock_pole_bracket','0035_stopcock_pole_clamp'),
        ('0035_stopcock_pole_clamp','0007_iv_pole')],
    'hanger_and_bags':[
        ('0007_iv_pole','0038_pole_hanger_socket'),
        ('0038_pole_hanger_socket','0018_hanger'),
        ('0018_hanger','0019_tube'),('0019_tube','0020_tube'),
        ('0018_hanger','0022_tube'),('0022_tube','0023_tube'),
        ('BAG1/0002_hanger_eye','0023_tube'),('BAG2/0002_hanger_eye','0020_tube'),
        ('BAG1/0002_hanger_eye','BAG1/0001_welded_seal'),
        ('BAG2/0002_hanger_eye','BAG2/0001_welded_seal')],
    'pole_base':[],
    'table_feet':[],
}
for _index in range(5):
    CONTACT_GROUPS['pole_base'].extend([
        ('0007_iv_pole',f'{8+_index*2:04d}_base_leg'),
        (f'{8+_index*2:04d}_base_leg',f'{9+_index*2:04d}_caster'),
        (f'{9+_index*2:04d}_caster',f'{39+_index:04d}_caster_floor_tread'),
        (f'{39+_index:04d}_caster_floor_tread','0000_training_room_floor')])
for _index in range(4):
    CONTACT_GROUPS['table_feet'].extend([
        (f'{2+_index:04d}_table_leg',f'{44+_index:04d}_table_floor_foot'),
        (f'{44+_index:04d}_table_floor_foot','0000_training_room_floor')])


def _part(meshes,suffix):
    matches=[mesh for name,mesh in meshes.items() if name.endswith(suffix)]
    assert len(matches)==1,('missing or ambiguous physical part',suffix,len(matches))
    return matches[0]


def _contact(a,b):
    """Closed-solid intersection/contact, with only 1 um export tolerance."""
    gap=np.maximum(np.maximum(a.bounds[0]-b.bounds[1],b.bounds[0]-a.bounds[1]),0.)
    if np.linalg.norm(gap)>1e-6:
        return False,{'separation_lower_bound_m':float(np.linalg.norm(gap))}
    meshes=[a.copy(),b.copy()]
    for mesh in meshes:
        mesh.process(validate=True)
        assert mesh.is_watertight and mesh.is_winding_consistent
    for source,target in (meshes,meshes[::-1]):
        field=vtk.vtkImplicitPolyDataDistance();field.SetInput(polydata(target))
        points=np.concatenate([source.vertices,source.triangles_center])
        values=vtk.vtkDoubleArray()
        field.EvaluateFunction(numpy_to_vtk(np.ascontiguousarray(points),deep=True),values)
        minimum=float(vtk_to_numpy(values).min())
        if minimum<=1e-6:
            return True,{'signed_distance_witness_m':minimum}
    collision=vtk.vtkCollisionDetectionFilter()
    for index,mesh in enumerate(meshes):
        collision.SetInputData(index,polydata(mesh))
        transform=vtk.vtkTransform();transform.Identity()
        collision.SetTransform(index,transform)
    collision.SetCollisionModeToFirstContact()
    collision.SetBoxTolerance(1e-8);collision.SetCellTolerance(1e-12)
    collision.Update()
    count=int(collision.GetNumberOfContacts())
    return bool(count),{'triangle_contacts':count}


def _body_meshes(meshes):
    return {name:mesh for name,mesh in meshes.items() if not name.endswith('_rotor')}


def _distances(mesh,points):
    solid=mesh.copy();solid.process(validate=True)
    field=vtk.vtkImplicitPolyDataDistance();field.SetInput(polydata(solid))
    values=vtk.vtkDoubleArray()
    field.EvaluateFunction(numpy_to_vtk(np.ascontiguousarray(points),deep=True),values)
    return vtk_to_numpy(values).copy()


def _assert_original_union_exterior(infusion,actual):
    old=list(_body_meshes(infusion['historical_stopcock']).values())
    body=list(_body_meshes(actual).values())
    combined=trimesh.util.concatenate(body)
    expected_bounds=np.array([np.min([mesh.bounds[0] for mesh in old],axis=0),
                              np.max([mesh.bounds[1] for mesh in old],axis=0)])
    np.testing.assert_allclose(combined.bounds,expected_bounds,atol=1e-7,rtol=0)
    for mesh in body:
        for original in old:
            for key in ('baseColorFactor','metallicFactor','roughnessFactor','doubleSided','alphaMode'):
                assert np.array_equal(getattr(mesh.visual.material,key),getattr(original.visual.material,key)),key
        assert mesh.visual.uv is None
        assert getattr(mesh.visual.material,'baseColorTexture',None) is None
        assert getattr(mesh.visual.material,'normalTexture',None) is None
        assert np.isfinite(mesh.vertex_normals).all()
        np.testing.assert_allclose(np.linalg.norm(mesh.vertex_normals,axis=1),1.,atol=1e-7)
        front=np.abs(mesh.triangles[:,:,1]-expected_bounds[0,1]).max(axis=1)<1e-9
        assert front.any()
        assert (mesh.vertex_normals[mesh.faces[front]][:,:,1]<-.999).all()
    candidate_points=np.concatenate([combined.vertices,combined.triangles_center])
    # Minimum signed distance represents the union. Interior surfaces of either
    # old component are deliberately not a required exterior feature.
    to_original=np.min([_distances(mesh,candidate_points) for mesh in old],axis=0)
    to_candidate=[];exposed_counts=[]
    for index,mesh in enumerate(old):
        points=np.concatenate([mesh.vertices,mesh.triangles_center])
        exposed=_distances(old[1-index],points)>=-1e-6
        exposed_counts.append(int(exposed.sum()))
        to_candidate.extend(np.abs(_distances(combined,points[exposed])).tolist())
    evidence={'candidate_surface_to_old_union_max_m':float(np.abs(to_original).max()),
              'old_exposed_surface_to_candidate_max_m':float(max(to_candidate)),
              'historical_exposed_samples':exposed_counts,'candidate_surface_samples':len(candidate_points),
              'surface_tolerance_m':.00005,'expected_bounds':expected_bounds.tolist(),
              'actual_bounds':combined.bounds.tolist()}
    (infusion['directory']/'union_exterior_preservation.json').write_text(json.dumps(evidence,indent=2))
    assert evidence['candidate_surface_to_old_union_max_m']<.00005,evidence
    assert evidence['old_exposed_surface_to_candidate_max_m']<.00005,evidence


@pytest.mark.parametrize('flavor',['local_generated','local_roundtrip'])
def test_stopcock_handle_pointer_is_one_closed_positive_volume_union(infusion,flavor):
    body=_body_meshes(infusion[flavor]['STOPCOCK'])
    topology=trimesh.util.concatenate(list(body.values()))
    topology.process(validate=True)
    x,y,z=infusion['baseline']['object_contracts']['STOPCOCK']['size_m']
    handle=cq.Workplane('XY').box(x,.009,.014).edges().fillet(.00144).translate((0,-y*.45,0))
    pointer=cq.Workplane('XY').box(.014,.009,z*.52).edges().fillet(.00144).translate((0,-y*.45,z*.18))
    expected_volume=handle.union(pointer).val().Volume()
    evidence={'body_nodes':list(body),'watertight':bool(topology.is_watertight),
              'winding_consistent':bool(topology.is_winding_consistent),
              'components':len(topology.split(only_watertight=False)),
              'mesh_volume_m3':float(topology.volume),'cad_union_volume_m3':expected_volume}
    (infusion['directory']/f'union_topology_{flavor}.json').write_text(json.dumps(evidence,indent=2))
    assert len(body)==1,evidence
    assert topology.is_watertight and topology.is_winding_consistent,evidence
    assert evidence['components']==1 and topology.volume>0,evidence
    assert topology.volume==pytest.approx(expected_volume,rel=.002),evidence


@pytest.mark.parametrize('flavor',['local_generated','local_roundtrip'])
def test_stopcock_shared_front_region_has_one_first_hit_surface(infusion,flavor):
    old=list(_body_meshes(infusion['historical_stopcock']).values())
    front_bounds=[]
    for mesh in old:
        front=np.abs(mesh.triangles[:,:,1]-mesh.bounds[0,1]).max(axis=1)<1e-9
        vertices=mesh.triangles[front].reshape(-1,3)
        front_bounds.append(np.array([vertices.min(axis=0),vertices.max(axis=0)]))
    low=np.maximum(front_bounds[0][0],front_bounds[1][0])[[0,2]]
    high=np.minimum(front_bounds[0][1],front_bounds[1][1])[[0,2]]
    points=np.random.default_rng(4701).uniform(low+1e-6,high-1e-6,(289,2))
    counts=np.zeros(len(points),int)
    for mesh in _body_meshes(infusion[flavor]['STOPCOCK']).values():
        front=np.abs(mesh.triangles[:,:,1]-mesh.bounds[0,1]).max(axis=1)<1e-9
        for triangle in mesh.triangles[front][:,:,[0,2]]:
            v0,v1,v2=triangle
            basis=np.column_stack([v1-v0,v2-v0])
            assert abs(np.linalg.det(basis))>1e-15
            uv=np.linalg.solve(basis,(points-v0).T).T
            counts+=((uv>=-1e-10).all(axis=1)&(uv.sum(axis=1)<=1+1e-10))
    evidence={'front_surface_counts':counts.tolist(),'sample_points_xz_m':points.tolist(),
              'minimum':int(counts.min()),'maximum':int(counts.max()),'samples':len(points)}
    (infusion['directory']/f'front_surface_multiplicity_{flavor}.json').write_text(json.dumps(evidence,indent=2))
    assert (counts==1).all(),evidence


@pytest.mark.parametrize('flavor',['generated','roundtrip'])
@pytest.mark.parametrize('group',CONTACT_GROUPS)
def test_infusion_load_paths_have_real_connected_solids(infusion,flavor,group):
    meshes=infusion[flavor];records=[]
    for first,second in CONTACT_GROUPS[group]:
        missing=[suffix for suffix in (first,second) if not any(name.endswith(suffix) for name in meshes)]
        if missing:
            records.append({'first':first,'second':second,'connected':False,'missing_parts':missing})
            continue
        connected,evidence=_contact(_part(meshes,first),_part(meshes,second))
        records.append({'first':first,'second':second,'connected':connected,**evidence})
    path=infusion['directory']/f'contacts_{flavor}_{group}.json'
    path.write_text(json.dumps(records,indent=2))
    assert all(row['connected'] for row in records),records


def test_infusion_ordered_insert_and_rotation_clear_all_roundtrip_obstacles(infusion,monkeypatch):
    spec=infusion['spec'].model_copy(deep=True)
    for obj in spec.objects:obj.asset=f'{obj.object_id}.glb'
    spec.environment[0].asset='workstation.glb'
    monkeypatch.setenv('HOLOCUE_ROOT',str(infusion['directory']))
    semantics=[CueSemantic(target_id=step.target_id,action=step.action,reference_id=step.reference_id,
        angle_deg=step.angle_deg,cue_type='ring_arrow' if step.action=='rotate' else 'ghost_motion',
        task_role='current' if index==0 else 'next',priority=5,depth_requirement=step.depth_requirement,
        instruction='Physical regression of declared ordered task')
        for index,step in enumerate(spec.task_contract.ordered_steps)]
    state=apply_decision(Session(session_id='infusion-support-regression',scene_id=spec.scene_id,
        backend_mode='geometry_validation'),Decision(operation='replace',assistant_message='Evaluate trajectory',
        cues=semantics),spec)
    objects={obj.object_id:obj for obj in spec.objects};records=[]
    for step in spec.task_contract.ordered_steps:
        display=packet(state,spec,infusion['policy']);cue=display.cues[0];source=objects[step.target_id]
        assert cue.target_id==source.object_id
        if step.action in ('insert','rotate'):
            scene=load_asset(str(infusion['directory']/source.asset),spec.asset_axes)
            mesh=scene.to_geometry()
            # Preserve audit_geometry.py's actual protocol and all obstacles.
            sampled,_=trimesh.sample.sample_surface(mesh,1536,seed=4701)
            names=[];distances=[]
            for name,part_mesh in _meshes(scene).items():
                part_mesh.process(validate=True)
                field=vtk.vtkImplicitPolyDataDistance();field.SetInput(polydata(part_mesh))
                values=vtk.vtkDoubleArray()
                field.EvaluateFunction(numpy_to_vtk(np.ascontiguousarray(sampled),deep=True),values)
                names.append(name);distances.append(np.abs(vtk_to_numpy(values)).copy())
            sample_parts=np.asarray(names)[np.argmin(np.asarray(distances),axis=0)]
            obstacle_objects=[obj.model_copy(update={'pose':display.object_poses[obj.object_id]})
                              for obj in spec.objects if obj.object_id!=source.object_id]
            obstacles,coverage=parts(spec,obstacle_objects+spec.environment)
            hits=[]
            for frame,t in enumerate(np.linspace(0,source.interaction.duration_s,41)):
                points=trimesh.transform_points(sampled,matrix(trajectory(cue,float(t))))
                lo=points.min(axis=0);hi=points.max(axis=0)
                for oid,name,bounds,field in obstacles:
                    if np.any(lo>bounds[1]) or np.any(hi<bounds[0]):continue
                    selection=((points>bounds[0]+.00075)&(points<bounds[1]-.00075)).all(axis=1)
                    if not selection.any():continue
                    values=vtk.vtkDoubleArray()
                    field.EvaluateFunction(numpy_to_vtk(np.ascontiguousarray(points[selection]),deep=True),values)
                    values_np=vtk_to_numpy(values);penetration=values_np<-.00075
                    if penetration.any():
                        source_names,counts=np.unique(sample_parts[selection][penetration],return_counts=True)
                        hits.append({'frame':frame,'elapsed_s':float(t),'obstacle':oid,'part':name,
                            'points':int(penetration.sum()),'max_depth_m':float(-values_np.min()),
                            'source_parts':{str(k):int(v) for k,v in zip(source_names,counts)}})
            records.append({'source':source.object_id,'action':step.action,'angle_deg':step.angle_deg,
                'sampled_surface_points':1536,'seed':4701,'trajectory_samples':41,'penetration_threshold_m':.00075,
                'penetrations':hits,'obstacle_coverage':coverage,
                'sampled_source_parts':{str(k):int((sample_parts==k).sum()) for k in names},
                'prior_completed':[task.semantic.model_dump(mode='json') for task in state.completed],
                'object_poses':{key:pose.model_dump(mode='json') for key,pose in display.object_poses.items()}})
        state=apply_decision(state,Decision(operation='complete',assistant_message='Complete audited step'),spec)
    (infusion['directory']/'sweep_records.json').write_text(json.dumps(records,indent=2))
    assert [row['source'] for row in records]==['PUMPCASSETTE','STOPCOCK']
    assert len(records[1]['prior_completed'])==2
    assert records[1]['angle_deg']==-90
    for row in records:
        assert not row['penetrations'],row
        assert not any(item['status']=='invalid_solid_topology' for item in row['obstacle_coverage']),row
